### ISSUE TITLE
make raspberry app configurable

### ISSUE THREAD

**Issue by lukaszkuczynski** [lukaszkuczynski/rss#4]
Following things need to be conifgurable:
- url
- name
- time

Exemplary config:
```yml
feeds:
- infopraca:
  url: info/rss
  cron: * * * s
```

Then make script using `python-crontab` to recreate feed crontabs.
Add to run.sh params from yml.
